### ISSUE TITLE
'Detect' object has no attribute 'm'

### ISSUE THREAD

**Issue by StevenFinch** [mikel-brostrom/Yolov5_DeepSort_Pytorch#10]
I am very confused. Pytorch=1.9 cuda=10.1
Thank u very much !

**Comment by mikel-brostrom** [comment]
It will be very hard to help you with this little information. Could you provide the complete error message?

**Comment by YexiongLin** [comment]
self.update(yaml.load(fo.read()))
Using CUDA device0 _CudaDeviceProperties(name='GeForce MX150', total_memory=2002MB)

/home/lyx/anaconda3/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'models.yolo.Model' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/lyx/anaconda3/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/lyx/anaconda3/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'models.yolo.Detect' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
1/1: 0...  success (640x480 at 30.00 FPS).

Traceback (most recent call last):
  File "track.py", line 247, in <module>
    detect(args)
  File "track.py", line 122, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "/home/lyx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "./yolov5/models/yolo.py", line 110, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "./yolov5/models/yolo.py", line 130, in forward_once
    x = m(x)  # run
  File "/home/lyx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "./yolov5/models/yolo.py", line 37, in forward
    x[i] = self.m[i](x[i])  # conv
  File "/home/lyx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Detect' object has no attribute 'm'
terminate called without an active exception

**Comment by YexiongLin** [comment]
> self.update(yaml.load(fo.read()))
> Using CUDA device0 _CudaDeviceProperties(name='GeForce MX150', total_memory=2002MB)
> 
> /home/lyx/anaconda3/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'models.yolo.Model' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
> warnings.warn(msg, SourceChangeWarning)
> /home/lyx/anaconda3/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
> warnings.warn(msg, SourceChangeWarning)
> /home/lyx/anaconda3/lib/python3.7/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'models.yolo.Detect' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
> warnings.warn(msg, SourceChangeWarning)
> 1/1: 0... success (640x480 at 30.00 FPS).
> 
> Traceback (most recent call last):
> File "track.py", line 247, in
> detect(args)
> File "track.py", line 122, in detect
> _ = model(img.half() if half else img) if device.type != 'cpu' else None # run once
> File "/home/lyx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "./yolov5/models/yolo.py", line 110, in forward
> return self.forward_once(x, profile) # single-scale inference, train
> File "./yolov5/models/yolo.py", line 130, in forward_once
> x = m(x) # run
> File "/home/lyx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "./yolov5/models/yolo.py", line 37, in forward
> x[i] = self.m[i](x%5Bi%5D) # conv
> File "/home/lyx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in **getattr**
> type(self).**name**, name))
> AttributeError: 'Detect' object has no attribute 'm'
> terminate called without an active exception
> 
> And pytorch=1.5.0 cuda=10.2 python=3.7
> The reason why I use pytorch 1.5.0 is that I can not run original yolov5 when I update my pytorch to 1.6.0

And I use python3.8 and pytorch 1.6.0, I met the same problem.

**Comment by Dreamskya** [comment]
同样遇到这个问题，有人解决了吗？

**Comment by Lamborxhini** [comment]
Traceback (most recent call last):
  File "track.py", line 247, in <module>
    detect(args)
  File "track.py", line 122, in detect
    _ = model(img.half() if half else img) if device.type != 'cpu' else None  # run once
  File "/home/jie311/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "./yolov5/models/yolo.py", line 100, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "./yolov5/models/yolo.py", line 120, in forward_once
    x = m(x)  # run
  File "/home/jie311/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "./yolov5/models/yolo.py", line 27, in forward
    x[i] = self.m[i](x[i])  # conv
  File "/home/jie311/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'Detect' object has no attribute 'm'
 
I encountered this problem, too. Need I upgrade my pytorch from 1.2.0 to 1.6.0 ? Or is it about my python version 3.6.10 ?Thanks @mikel-brostrom 

请问有哪位大佬解决了这个问题么？可以的话交流一下谢谢！

**Comment by mikel-brostrom** [comment]
Make sure that **ALL** requirements are fulfilled: Python >= 3.7, PyTorch >= 1.5 etc.
Then make sure both your both and models are up to date. If in doubt, simply start from a clean slate: reclone the repo and download new weights

**Comment by Lamborxhini** [comment]
Thanks buddy ！ I'll try to figure it out under your advice and hope this problem will not puzzle me that longer.&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikel-brostrom/Yolov5_DeepSort_Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 晚上6:03
收件人:&nbsp;"mikel-brostrom/Yolov5_DeepSort_Pytorch"<Yolov5_DeepSort_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"「辰雲·苍曦」"<percy_dwan@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [mikel-brostrom/Yolov5_DeepSort_Pytorch] 'Detect' object has no attribute 'm' (#10)





 
Make sure that ALL requirements are fulfilled: Python &gt;= 3.7, PyTorch &gt;= 1.5 etc.
 Then make sure both your both and models are up to date. If in doubt, simply start from a clean slate: reclone the repo and download new weights

**Comment by mikel-brostrom** [comment]
For more info on this specific error you could check:
* https://github.com/ultralytics/yolov5/issues/690

**Comment by Jiachenyin1** [comment]
> For more info on this specific error you could check:
> 
> * [ultralytics/yolov5#690](https://github.com/ultralytics/yolov5/issues/690)

yes  solve it  Thx

**Comment by mikel-brostrom** [comment]
I just updated yolov5. That may help as well

**Comment by mikel-brostrom** [comment]
I encountered this same error myself yesterday while updating yolov5. I updated the code but didn't update the models, so... https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/issues/10#issuecomment-679930882
